# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: instruments.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require_relative 'instruments_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module InstrumentsService
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.InstrumentsService'

                # Метод получения расписания торгов торговых площадок.
                rpc :TradingSchedules, ::Tinkoff::Public::Invest::Api::Contract::V1::TradingSchedulesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::TradingSchedulesResponse
                # Метод получения облигации по её идентификатору.
                rpc :BondBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::BondResponse
                # Метод получения списка облигаций.
                rpc :Bonds, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::BondsResponse
                # Метод получения графика выплат купонов по облигации.
                rpc :GetBondCoupons, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBondCouponsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetBondCouponsResponse
                # Метод получения валюты по её идентификатору.
                rpc :CurrencyBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::CurrencyResponse
                # Метод получения списка валют.
                rpc :Currencies, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::CurrenciesResponse
                # Метод получения инвестиционного фонда по его идентификатору.
                rpc :EtfBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::EtfResponse
                # Метод получения списка инвестиционных фондов.
                rpc :Etfs, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::EtfsResponse
                # Метод получения фьючерса по его идентификатору.
                rpc :FutureBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::FutureResponse
                # Метод получения списка фьючерсов.
                rpc :Futures, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::FuturesResponse
                # Метод получения опциона по его идентификатору.
                rpc :OptionBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::OptionResponse
                # Deprecated Метод получения списка опционов.
                rpc :Options, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::OptionsResponse
                # Метод получения списка опционов.
                rpc :OptionsBy, ::Tinkoff::Public::Invest::Api::Contract::V1::FilterOptionsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::OptionsResponse
                # Метод получения акции по её идентификатору.
                rpc :ShareBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::ShareResponse
                # Метод получения списка акций.
                rpc :Shares, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::SharesResponse
                # Метод получения накопленного купонного дохода по облигации.
                rpc :GetAccruedInterests, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccruedInterestsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccruedInterestsResponse
                # Метод получения размера гарантийного обеспечения по фьючерсам.
                rpc :GetFuturesMargin, ::Tinkoff::Public::Invest::Api::Contract::V1::GetFuturesMarginRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetFuturesMarginResponse
                # Метод получения основной информации об инструменте.
                rpc :GetInstrumentBy, ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::InstrumentResponse
                # Метод для получения событий выплаты дивидендов по инструменту.
                rpc :GetDividends, ::Tinkoff::Public::Invest::Api::Contract::V1::GetDividendsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetDividendsResponse
                # Метод получения актива по его идентификатору.
                rpc :GetAssetBy, ::Tinkoff::Public::Invest::Api::Contract::V1::AssetRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::AssetResponse
                # Метод получения списка активов. Метод работает для всех инструментов, за исключением срочных - опционов и фьючерсов.
                rpc :GetAssets, ::Tinkoff::Public::Invest::Api::Contract::V1::AssetsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::AssetsResponse
                # Метод получения списка избранных инструментов.
                rpc :GetFavorites, ::Tinkoff::Public::Invest::Api::Contract::V1::GetFavoritesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetFavoritesResponse
                # Метод редактирования списка избранных инструментов.
                rpc :EditFavorites, ::Tinkoff::Public::Invest::Api::Contract::V1::EditFavoritesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::EditFavoritesResponse
                # Метод получения списка стран.
                rpc :GetCountries, ::Tinkoff::Public::Invest::Api::Contract::V1::GetCountriesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetCountriesResponse
                # Метод поиска инструмента.
                rpc :FindInstrument, ::Tinkoff::Public::Invest::Api::Contract::V1::FindInstrumentRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::FindInstrumentResponse
                # Метод получения списка брендов.
                rpc :GetBrands, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBrandsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetBrandsResponse
                # Метод получения бренда по его идентификатору.
                rpc :GetBrandBy, ::Tinkoff::Public::Invest::Api::Contract::V1::GetBrandRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::Brand
              end

              Stub = Service.rpc_stub_class
            end
            # Сервис предназначен для получения:</br>**1**. информации об инструментах;</br>**2**.
            # расписания торговых сессий;</br>**3**. календаря выплат купонов по облигациям;</br>**4**.
            # размера гарантийного обеспечения по фьючерсам;</br>**5**. дивидендов по ценной бумаге.
          end
        end
      end
    end
  end
end
