# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: marketdata.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require_relative 'marketdata_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module MarketDataService
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.MarketDataService'

                # Метод запроса исторических свечей по инструменту.
                rpc :GetCandles, ::Tinkoff::Public::Invest::Api::Contract::V1::GetCandlesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetCandlesResponse
                # Метод запроса цен последних сделок по инструментам.
                rpc :GetLastPrices, ::Tinkoff::Public::Invest::Api::Contract::V1::GetLastPricesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetLastPricesResponse
                # Метод получения стакана по инструменту.
                rpc :GetOrderBook, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderBookRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderBookResponse
                # Метод запроса статуса торгов по инструментам.
                rpc :GetTradingStatus, ::Tinkoff::Public::Invest::Api::Contract::V1::GetTradingStatusRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetTradingStatusResponse
                # Метод запроса статуса торгов по инструментам.
                rpc :GetTradingStatuses, ::Tinkoff::Public::Invest::Api::Contract::V1::GetTradingStatusesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetTradingStatusesResponse
                # Метод запроса обезличенных сделок за последний час.
                rpc :GetLastTrades, ::Tinkoff::Public::Invest::Api::Contract::V1::GetLastTradesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetLastTradesResponse
                # Метод запроса цен закрытия торговой сессии по инструментам.
                rpc :GetClosePrices, ::Tinkoff::Public::Invest::Api::Contract::V1::GetClosePricesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetClosePricesResponse
              end

              Stub = Service.rpc_stub_class
            end

            # Сервис получения биржевой информации:</br> **1**. свечи;</br> **2**. стаканы;</br> **3**. торговые статусы;</br> **4**. лента сделок.
            module MarketDataStreamService
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.MarketDataStreamService'

                # Bi-directional стрим предоставления биржевой информации.
                rpc :MarketDataStream, stream(::Tinkoff::Public::Invest::Api::Contract::V1::MarketDataRequest),
                    stream(::Tinkoff::Public::Invest::Api::Contract::V1::MarketDataResponse)
                # Server-side стрим предоставления биржевой информации.
                rpc :MarketDataServerSideStream,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::MarketDataServerSideStreamRequest, stream(::Tinkoff::Public::Invest::Api::Contract::V1::MarketDataResponse)
              end

              Stub = Service.rpc_stub_class
            end
          end
        end
      end
    end
  end
end
