# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: orders.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require './lib/orders_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module OrdersStreamService
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.OrdersStreamService'

                # Stream сделок пользователя
                rpc :TradesStream, ::Tinkoff::Public::Invest::Api::Contract::V1::TradesStreamRequest,
                    stream(::Tinkoff::Public::Invest::Api::Contract::V1::TradesStreamResponse)
              end

              Stub = Service.rpc_stub_class
            end

            module OrdersService
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.OrdersService'

                # Метод выставления заявки.
                rpc :PostOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderResponse
                # Метод отмены биржевой заявки.
                rpc :CancelOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelOrderRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::CancelOrderResponse
                # Метод получения статуса торгового поручения.
                rpc :GetOrderState, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrderStateRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::OrderState
                # Метод получения списка активных заявок по счёту.
                rpc :GetOrders, ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrdersRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetOrdersResponse
                # Метод изменения выставленной заявки.
                rpc :ReplaceOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::ReplaceOrderRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::PostOrderResponse
              end

              Stub = Service.rpc_stub_class
            end
            # Сервис предназначен для работы с торговыми поручениями:</br> **1**.
            # выставление;</br> **2**. отмена;</br> **3**. получение статуса;</br> **4**.
            # расчёт полной стоимости;</br> **5**. получение списка заявок.
          end
        end
      end
    end
  end
end
