# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: sandbox.proto for package ''

require 'grpc'
require 'sandbox_pb'

module SandboxService
  class Service

    include ::GRPC::GenericService
    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'SandboxService'

    # Метод регистрации счёта в песочнице.
    rpc :OpenSandboxAccount, ::OpenSandboxAccountRequest, ::OpenSandboxAccountResponse
    # Метод получения счетов в песочнице.
    rpc :GetSandboxAccounts, ::GetAccountsRequest, ::GetAccountsResponse
    # Метод закрытия счёта в песочнице.
    rpc :CloseSandboxAccount, ::CloseSandboxAccountRequest, ::CloseSandboxAccountResponse
  end

  Stub = Service.rpc_stub_class
end
# Сервис для работы с песочницей TINKOFF INVEST API
