# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: stoporders.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require 'stoporders_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module StopOrdersService
              class Service

                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.StopOrdersService'

                # Метод выставления стоп-заявки.
                rpc :PostStopOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::PostStopOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::PostStopOrderResponse
                # Метод получения списка активных стоп заявок по счёту.
                rpc :GetStopOrders, ::Tinkoff::Public::Invest::Api::Contract::V1::GetStopOrdersRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::GetStopOrdersResponse
                # Метод отмены стоп-заявки.
                rpc :CancelStopOrder, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelStopOrderRequest, ::Tinkoff::Public::Invest::Api::Contract::V1::CancelStopOrderResponse
              end

              Stub = Service.rpc_stub_class
            end
            # Сервис предназначен для работы со стоп-заявками:</br> **1**.
            # выставление;</br> **2**. отмена;</br> **3**. получение списка стоп-заявок.
          end
        end
      end
    end
  end
end
