# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: users.proto for package 'tinkoff.public.invest.api.contract.v1'

require 'grpc'
require_relative 'users_pb'

module Tinkoff
  module Public
    module Invest
      module Api
        module Contract
          module V1
            module UsersService
              class Service
                include ::GRPC::GenericService

                self.marshal_class_method = :encode
                self.unmarshal_class_method = :decode
                self.service_name = 'tinkoff.public.invest.api.contract.v1.UsersService'

                # Метод получения счетов пользователя.
                rpc :GetAccounts, ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccountsRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetAccountsResponse
                # Расчёт маржинальных показателей по счёту.
                rpc :GetMarginAttributes, ::Tinkoff::Public::Invest::Api::Contract::V1::GetMarginAttributesRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetMarginAttributesResponse
                # Запрос тарифа пользователя.
                rpc :GetUserTariff, ::Tinkoff::Public::Invest::Api::Contract::V1::GetUserTariffRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetUserTariffResponse
                # Метод получения информации о пользователе.
                rpc :GetInfo, ::Tinkoff::Public::Invest::Api::Contract::V1::GetInfoRequest,
                    ::Tinkoff::Public::Invest::Api::Contract::V1::GetInfoResponse
              end

              Stub = Service.rpc_stub_class
            end
            # Сервис предназначен для получения: </br> **1**.
            # списка счетов пользователя; </br> **2**. маржинальных показателей по счёту.
          end
        end
      end
    end
  end
end
